[package]
name = "horcrux-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
sharks = "0.4"
serde = { version = "1.0", features = ["derive"] }
aes = "0.8.2"
clap = { version = "4.2.7", features = ["derive"] }
