name: Publisher
on:
  workflow_dispatch:
  release:
    types:
      - published
jobs:
  cratey:
    name: Upload to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
  chocolatey:
    name: Upload to chocolatey!. Chocolate time!
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build on windows
        run: cargo build --release
      - name: Set up chocolatey workspace # Download artifact unzip, and move to tools directory. 
        run: |
          mkdir tools
          cp "target/release/horcrust.exe" tools/
          cp "LICENSE.txt" tools/
      - name: Generate nuspec template
        run: |
          echo '<?xml version="1.0"?>' > horcrust.nuspec
          echo '<package>' >> horcrust.nuspec
          echo '  <metadata>' >> horcrust.nuspec
          echo '    <id>horcrust</id>' >> horcrust.nuspec
          echo '    <version>${{ github.ref_name }}</version>' >> horcrust.nuspec
          echo '    <title>horcrust</title>' >> horcrust.nuspec
          echo '    <authors>ccline</authors>' >> horcrust.nuspec
          echo '    <projectUrl>https://github.com/codycline/horcrux-rs</projectUrl>' >> horcrust.nuspec
          echo '    <description>Horcrust is a command-line-tool which splits a file into encrypted shards for safekeeping. As long as the specified threshold is met, a user can resurrect their original file at any time - no password necessary.</description>' >> horcrust.nuspec
          echo '    <tags>encryption cli rust</tags>' >> horcrust.nuspec
          echo '  </metadata>' >> horcrust.nuspec
          echo '  <files>' >> horcrust.nuspec
          echo '    <file src="tools\**" target="tools" />' >> horcrust.nuspec
          echo '  </files>' >> horcrust.nuspec
          echo '</package>' >> horcrust.nuspec
      - name: Create VERIFICATION.txt
        run: |
          echo 'Generated by `CertUtil -hashfile horcrust.exe SHA256`: \r\n' > tools/VERIFICATION.txt
          echo $(CertUtil -hashfile tools\horcrust.exe SHA256) >> tools/VERIFICATION.txt
      - name: Create chocolatey package
        run: choco pack horcrust.nuspec
      - name: Publish on chocolatey
        run: choco push horcrust.${{ github.ref_name }}.nupkg -s https://push.chocolatey.org/ --api-key=${{ secrets.CHOCOLATEY_API_KEY }}

  # brewster:
  #   name: Upload to chocolatey!. Chocolate time!
  #   runs-on: macos-latest
  #   steps:
  #     - name: bump brew
  #       run: ''