name: Publisher
on:
  workflow_dispatch:
  release:
    types: [published] 
jobs:
  crates:
    name: 📦 Upload to crates.io 📦
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Get published crate version from crates.io
        run: |
          echo PUBLISHED_VERSION=$(cargo search horcrust | grep horcrust |  awk '{print $3}' | tr -d '"') >> $GITHUB_OUTPUT
      
      - name: Get local cargo version from Cargo.toml
        run: |
          echo LOCAL_VERSION=$(grep -oP '^version = "\K[^"]+' Cargo.toml)
      
      #In case of manual trigger this ensures we don't try to publish the exact crate
      - run: cargo publish --token ${CRATES_TOKEN} 
        if: ${{ env.LOCAL_VERSION != env.PUBLISHED_VERSION }}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
  chocolatey:
    name: 🍫 Upload to chocolatey. Chocolate time! 🍫🍫🍫
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Normalize release version #removes the v prefix
        run: |
          $currentTag = '${{ github.ref_name }}'
          echo ("VERSION=" + $currentTag.replace('v', '')) | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build on windows
        run: cargo build --release
      - name: Set up chocolatey workspace 
        run: |
          mkdir tools
          cp "target/release/horcrust.exe" tools/
          cp "LICENSE.txt" tools/
      - name: Generate nuspec template
        run: |
          echo '<?xml version="1.0"?>' > horcrust.nuspec
          echo '<package>' >> horcrust.nuspec
          echo '  <metadata>' >> horcrust.nuspec
          echo '    <id>horcrust</id>' >> horcrust.nuspec
          echo '    <version>${{ env.VERSION }}</version>' >> horcrust.nuspec
          echo '    <title>horcrust</title>' >> horcrust.nuspec
          echo '    <authors>ccline</authors>' >> horcrust.nuspec
          echo '    <projectUrl>https://github.com/codycline/horcrux-rs</projectUrl>' >> horcrust.nuspec
          echo '    <description>Horcrust is a command-line-tool which splits a file into encrypted shards for safekeeping. As long as the specified threshold is met, a user can resurrect their original file at any time - no password necessary.</description>' >> horcrust.nuspec
          echo '    <tags>encryption cli rust</tags>' >> horcrust.nuspec
          echo '  </metadata>' >> horcrust.nuspec
          echo '  <files>' >> horcrust.nuspec
          echo '    <file src="tools\**" target="tools" />' >> horcrust.nuspec
          echo '  </files>' >> horcrust.nuspec
          echo '</package>' >> horcrust.nuspec
      - name: Create VERIFICATION.txt
        run: |
          echo 'Generated by `CertUtil -hashfile horcrust.exe SHA256`: \r\n' > tools/VERIFICATION.txt
          echo $(CertUtil -hashfile tools\horcrust.exe SHA256) >> tools/VERIFICATION.txt
      - name: Create chocolatey package
        run: choco pack horcrust.nuspec
      - name: Publish on chocolatey
        run: choco push horcrust.${{ env.VERSION }}.nupkg -s https://push.chocolatey.org/ --api-key=${{ secrets.CHOCOLATEY_API_KEY }}

  # brew:
  #   name: 🍺 Publish to homebrew 🍺
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Install rust toolchain
  #       uses: dtolnay/rust-toolchain@stable

  #     - name: Build on macos
  #       run: cargo build --release
      
  #     - name: Compress artifact
  #       run: |
  #         cp target/release/horcrust .
  #         tar -czf horcrust-${{ github.ref_name }}-apple-darwin.tar.gz horcrust
      
  #     - name: Set shasum 
  #       run: echo SHASUM=$(shasum horcrust-${{ github.ref_name }}-apple-darwin.tar.gz | awk '{printf $1}') >> $GITHUB_OUTPUT
      
  #     - name: 🍺 Bump Brew
        
  #       run: |
  #         brew tap tgotwig/homebrew-vidmerger
  #         brew bump-formula-pr -f --version=${{ steps.get_version.outputs.version }} --no-browse --no-audit \
  #         --sha256=${{ env.SHASUM }} \
  #         --url='https://github.com/tgotwig/vidmerger/releases/download/${{ steps.get_version.outputs.version }}/vidmerger-mac.tar.gz' \
  #         tgotwig/homebrew-vidmerger/vidmerger
  #       env:
  #         BREW_TOKEN: ${{ secrets.BREW_TOKEN }}