name: Releaser
on: 
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build_mac:
    name: Build for macOS
    runs-on: macos-latest
    outputs:
      artifact: ${{ steps.package.outputs.artifact }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build on macOS
        run: cargo build --release
      - name: Zip artifact
        run: tar -czf hx-1.0.0-x86_64-apple-darwin.tar.gz ./target/release/hx
      - id: package
        name: Output the artifact
        run: echo "artifact=hx-1.0.0-x86_64-apple-darwin.tar.gz" >> $GITHUB_OUTPUT
  create_release:
    name: Create GitHub Release
    needs: [build_mac]
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: echo ${{ github.sha }} > release.txt
      - name: Test
        run: cat release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        env: 
          ARTIFACT: ${{needs.job1.outputs.artifact}}
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: v1.0.0
          tag_name: v1.0.0
          files: |
            $ARTIFACT
            release.txt
            LICENSE
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"