name: Releaser
on: 
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  build_mac:
    name: Build for macOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build on macOS
        run: cargo build --release
      - name: Zip artifact
        run: tar -czf hx-1.0.0-x86_64-apple-darwin.tar.gz ./target/release/hx
      - id: artifact
        name: Output the artifact
        run: echo "artifact=hx-1.0.0-x86_64-apple-darwin.tar.gz" >> $GITHUB_OUTPUT
  create_release:
    name: Create GitHub Release
    needs: [build_mac]
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: echo ${{ github.sha }} > release.txt
      - name: Test
        run: cat release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: v1.0.0
          files: |
            ${{needs.build_mac.outputs.artifact}}
            release.txt
            LICENSE