name: Tester
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Test platform
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run all tests
        run: cargo test -- --test-threads=1

